"""GitHub REST API wrapper for repository file access and issue creation."""

from __future__ import annotations

from pathlib import PurePosixPath

from github import Auth, Github, GithubException


# File extensions considered as source code by default.
DEFAULT_CODE_EXTENSIONS = (
    ".py",
    ".js",
    ".ts",
    ".jsx",
    ".tsx",
    ".java",
    ".c",
    ".cpp",
    ".cs",
    ".go",
    ".rb",
    ".php",
    ".html",
    ".css",
    ".scss",
    ".sh",
    ".rs",
    ".kt",
    ".swift",
)

# Maximum individual file size (bytes) to attempt decoding.
MAX_FILE_BYTES = 100_000

# Reviews should keep the most relevant source files in context instead of
# dumping every file, otherwise the local model loses the main execution path.
REVIEW_FILE_LIMIT = 4
PRIORITY_KEYWORDS = (
    "mainactivity",
    "main",
    "app",
    "index",
    "server",
    "program",
    "entry",
    "screen",
    "nav",
    "navigation",
    "route",
    "controller",
    "service",
    "view",
    "page",
)

ENTRY_FILENAMES = {
    "mainactivity.kt",
    "main.py",
    "main.js",
    "main.ts",
    "index.js",
    "index.ts",
    "app.js",
    "app.ts",
    "app.py",
    "program.cs",
}

# Directories commonly generated by package managers, build pipelines, or IDEs.
IGNORED_DIRECTORIES = {
    ".git",
    ".idea",
    ".next",
    ".venv",
    "__pycache__",
    "android/build",
    "build",
    "dist",
    "ios/Pods",
    "node_modules",
    "Pods",
    "target",
}


class GitHubClient:
    """Thin wrapper around PyGithub for the operations this tool needs."""

    def __init__(self, token: str) -> None:
        self.g = Github(auth=Auth.Token(token))

    # ------------------------------------------------------------------
    # Repository file reading
    # ------------------------------------------------------------------

    def get_repo_files(
        self,
        repo_full_name: str,
        extensions: list[str] | None = None,
    ) -> dict[str, str]:
        """Return a mapping of ``path -> text content`` for a repository.

        Parameters
        ----------
        repo_full_name:
            GitHub repository in ``owner/repo`` format.
        extensions:
            Whitelist of file extensions (e.g. ``[".py", ".js"]``).
            If *None* or empty the :data:`DEFAULT_CODE_EXTENSIONS` set is used.
        """
        allowed = tuple(extensions) if extensions else DEFAULT_CODE_EXTENSIONS
        repo = self.g.get_repo(repo_full_name)
        files: dict[str, str] = {}
        self._traverse(repo, "", files, allowed)
        return self._select_relevant_files(files, allowed)

    def _traverse(
        self,
        repo,
        path: str,
        files: dict[str, str],
        extensions: tuple[str, ...],
    ) -> None:
        try:
            contents = repo.get_contents(path)
        except GithubException:
            return

        if not isinstance(contents, list):
            contents = [contents]

        for item in contents:
            if item.type == "dir":
                if self._should_skip_dir(item.path):
                    continue
                self._traverse(repo, item.path, files, extensions)
            elif item.type == "file":
                if item.path.endswith(extensions) and item.size <= MAX_FILE_BYTES:
                    try:
                        files[item.path] = item.decoded_content.decode(
                            "utf-8", errors="replace"
                        )
                    except Exception:
                        pass

    @staticmethod
    def _should_skip_dir(path: str) -> bool:
        normalized = path.strip("/")
        return any(
            normalized == ignored or normalized.startswith(f"{ignored}/")
            for ignored in IGNORED_DIRECTORIES
        )

    @classmethod
    def _select_relevant_files(
        cls,
        files: dict[str, str],
        extensions: tuple[str, ...],
    ) -> dict[str, str]:
        if not files:
            return files

        if len(files) <= REVIEW_FILE_LIMIT:
            return files

        ranked_paths = sorted(files, key=cls._relevance_key)
        selected_paths = ranked_paths[:REVIEW_FILE_LIMIT]
        return {path: files[path] for path in selected_paths}

    @staticmethod
    def _relevance_key(path: str) -> tuple[int, int, str]:
        filename = PurePosixPath(path).name.lower()
        score = 100

        if filename in ENTRY_FILENAMES:
            score -= 60

        if filename.endswith("screen.kt"):
            score -= 35

        if any(keyword in filename for keyword in PRIORITY_KEYWORDS):
            score -= 20

        if "/test" in path.lower() or filename.startswith("test_") or filename.endswith("_test.py"):
            score += 40

        return (score, len(path), path.lower())

    # ------------------------------------------------------------------
    # Issue creation
    # ------------------------------------------------------------------

    def create_issue(
        self,
        repo_full_name: str,
        title: str,
        body: str,
    ) -> str:
        """Create a GitHub issue and return its URL.

        Parameters
        ----------
        repo_full_name:
            GitHub repository in ``owner/repo`` format.
        title:
            Issue title.
        body:
            Issue body (Markdown).

        Returns
        -------
        str
            The HTML URL of the created issue.
        """
        repo = self.g.get_repo(repo_full_name)
        issue = repo.create_issue(title=title, body=body)
        return issue.html_url
